
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muhammad Dzaky
 */
public class TebakGambarJFrame extends javax.swing.JFrame {
        private Game game;
        private boolean benar = false; 
        
        
                
              
        public TebakGambarJFrame() {
        initComponents();
        
        bNext.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Answer = new javax.swing.JTextField();
        bSubmit = new javax.swing.JButton();
        bSLevel = new javax.swing.JButton();
        ScorePlayer = new javax.swing.JLabel();
        bNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gambar");

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ImagePanelLayout.setVerticalGroup(
            ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        Answer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerActionPerformed(evt);
            }
        });
        Answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AnswerKeyPressed(evt);
            }
        });

        bSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8-checked-checkbox-26.png"))); // NOI18N
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });
        bSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bSubmitKeyPressed(evt);
            }
        });

        bSLevel.setBackground(new java.awt.Color(0, 0, 0));
        bSLevel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        bSLevel.setForeground(new java.awt.Color(255, 255, 255));
        bSLevel.setText("Select Level");
        bSLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSLevelActionPerformed(evt);
            }
        });

        ScorePlayer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        ScorePlayer.setForeground(new java.awt.Color(255, 255, 255));
        ScorePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScorePlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8-score-26.png"))); // NOI18N

        bNext.setBackground(new java.awt.Color(0, 0, 0));
        bNext.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        bNext.setForeground(new java.awt.Color(255, 255, 255));
        bNext.setText("Next");
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScorePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Answer, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(bSLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bNext, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScorePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Answer))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSLevelActionPerformed
        PageLevel page = new PageLevel();
        page.setGame(game);
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_bSLevelActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        if (game != null) {
            String jawaban = Answer.getText().trim();
            if (jawaban.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jawaban kamu kosong");
                return;
            }

            if (game.checkAnswer(jawaban)) {
                int currentLevel = game.getCurrentLevel();
                if (game.getPlayer().levelBeresCek(currentLevel)){
                    JOptionPane.showMessageDialog(this, "Lanjut ke level berikutnya!");
                } else {
                    boolean tambahScore = game.getPlayer().incrementScore(currentLevel);
                    if(tambahScore){
                        JOptionPane.showMessageDialog(this, "Jawaban benar!!!");
                    }
                }
                benar = true;
                bNext.setEnabled(true);
                bSubmit.setEnabled(false);
                Answer.setEditable(false);
                ScorePlayer.setText(" " + game.getPlayer().getScore());
                
            } else {
                JOptionPane.showMessageDialog(this, "Jawaban salah. Coba lagi");
                benar = false;
                bNext.setEnabled(false);
            }
        }
    }//GEN-LAST:event_bSubmitActionPerformed

    private void AnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerActionPerformed

    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed
        if(game != null && benar){
            if(game.hasNextQuestion()){
                game.nextQuestion();
                benar = false;
                bNext.setEnabled(false);
                tampilkanSoal();
            } 
        }
    }//GEN-LAST:event_bNextActionPerformed

    private void bSubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bSubmitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSubmitKeyPressed

    private void AnswerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnswerKeyPressed
        
    }//GEN-LAST:event_AnswerKeyPressed

    private void tampilkanSoal() {
        if (game != null && !game.isGameOver()) {
            Question q = game.getCurrentQuestion();
            if(q != null){
                loadAndDisplayImage(q.getImagePath());
                Answer.setText("");
                Answer.setEditable(true);
                bSubmit.setEnabled(true);
                benar = false;
                ScorePlayer.setText(" " + game.getPlayer().getScore());
                bNext.setEnabled(benar);
                this.setTitle("Level " + game.getCurrentLevel());
            } else {
                JOptionPane.showMessageDialog(this, "tidak ada soal yang tersedia");
            }
        }
    }
    
    private void loadAndDisplayImage(String imagePath){
        try {
            File imageFile = new File(imagePath);
            if(!imageFile.exists()){
                JOptionPane.showMessageDialog(this, "Gambar tidak ditemukan");
                jLabel2.setText("Gambar tidak ada di File");
                jLabel2.setIcon(null);
                return;
            }
            
            BufferedImage originalImage = ImageIO.read(imageFile); //untuk meload gambarnya
            int lw = jLabel2.getWidth();
            int lh = jLabel2.getHeight();
            Image scaledImage = originalImage.getScaledInstance(lw, lh, Image.SCALE_SMOOTH);
            jLabel2.setIcon(new ImageIcon(scaledImage));
            jLabel2.setText("");
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gambar gagal diload " + e.getMessage());
        }
    }
    
    public void setGame(Game game) {
        this.game = game;
        if (game != null){
            tampilkanSoal(); 
        } 
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakGambarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakGambarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakGambarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakGambarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakGambarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel ScorePlayer;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bSLevel;
    private javax.swing.JButton bSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}